# Site settings
title: CV - Mróz Krzysztof
tag_text: CV
description: CV - Mróz Krzysztof 
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
